### PR TITLE
Development

### PR DESCRIPTION
**Pull request by dudi2022**
I've made a lot of updates according to the issues.

I'm a bit stuck on authorisation: keep getting a 401 when I run the search:

image

I will come back to this tomorrow/ tonight after dinner

### CODE REVIEW

**Comment by dudi2022** [comment]
made some changes but same issue:

image

I will come back to this later :-)

**Review by marco-svitol — APPROVED** [review]

**Comment by dudi2022** [comment]
Got it - thank you - I will do this today

**Comment by dudi2022** [comment]
I updated the call this morning and tried a few different ways, kept adding
things to the API call to check the refreshtoken expiry etc. still getting
401. I will come back to this later. Maybe you can see some mistakes that I
made in here?

[image: image.png]

[image: image.png]

Am Di., 18. Apr. 2023 um 21:56 Uhr schrieb Marco ***@***.***>:

**Comment by dudi2022** [comment]
did some tweaks but still the same

[image: image.png]

Am Mi., 19. Apr. 2023 um 05:51 Uhr schrieb William Beatty <
***@***.***>:

**Comment by dudi2022** [comment]
this is how the call currently stands. sorry for spamming you...

[image: image.png][image: image.png]

Am Mi., 19. Apr. 2023 um 07:10 Uhr schrieb William Beatty <
***@***.***>:

**Pull request merged**
